package br.com.newe.ms_veiculos.dto;

import java.time.LocalDate;

public record OperacionalResponseDTO(
                String manifesto,
                String filial,
                LocalDate data,
                String motorista,
                String cpf,
                String pis,
                LocalDate dataNascimento,
                String enderecoMotorista,
                String cepMotorista,
                String bairroMotorista,
                String cidadeMotorista,
                String estadoMotorista,
                String chefeGuarnicao,
                String vigilante1,
                String vigilante2,
                String agregado,
                String cpfCnpjAgregado,
                String pisAgregado,
                String regimeFiscal,
                String veiculo,
                String reboque1,
                String reboque2,
                String reboque3,
                String destino,
                String servicos,
                String nfs,
                Double kgReal,
                Double kgTaxado,
                Double m3,
                String servicosFinalizados,
                Double percentualEfetividade,
                Double capacidadeVeiculo,
                Double percentualAprovVeiculo,
                Double kmSaida,
                Double kmChegada,
                Integer coletas,
                Integer entregas,
                Integer despachos,
                Integer retiradas,
                Integer coletasReversa,
                String classificacao,
                String observacoesOperacionais,
                String status,
                String usuario) {
}
