spring.application.name=ms-veiculos
spring.security.user.name=api
spring.security.user.password=123456

spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration