# 1. URL de Conexão com o seu banco Supabase
# Lembre-se de trocar [SEU-HOST] pelo endereço real fornecido lá no painel do Supabase
spring.datasource.url=jdbc:postgresql://[SEU-HOST].supabase.co:5432/postgres?sslmode=require

# 2. Credenciais de acesso
spring.datasource.username=postgres
spring.datasource.password=coloque_sua_senha_aqui_cuidado_para_nao_enviar_pro_github

# 3. Qual banco estamos usando (PostgreSQL)
spring.datasource.driver-class-name=org.postgresql.Driver

# 4. Configurações do Hibernate (ORM)
# Como o banco já existe com os dados reais, o validate apenas checa se os Models estão certos
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 5. Opcional, mas muito útil: Mostra no terminal o SQL que o Spring está executando por trás dos panos
spring.jpa.show-sql=true